### ISSUE TITLE
why

### ISSUE THREAD

**Issue by sandysameh** [utopia-os/utopia-ui#1]
ERROR in ./src/components/map/map.js 49:35-44

export 'default' (imported as 'UtopiaMap') was not found in 'utopia-ui' (possible exports: Item, Layer, Tags, UtopiaMap, __esModule)

ERROR in ./node_modules/utopia-ui/node_modules/react-leaflet-cluster/lib/index.js 29:13-43

Module not found: Error: Can't resolve '@react-leaflet/core' in 'F:\Courses\Mern Stack Projects Crash COurse\Cypod\client\node_modules\utopia-ui\node_modules\react-leaflet-cluster\lib'

**Comment by antontranelis** [comment]
I guess you try to import `UtopiaMap` without the braces. You have to import `UtopiaMap` as named import.

Use import `import { UtopiaMap } from 'utopia-ui'` instead of `import UtopiaMap from 'utopia-ui'`
