### ISSUE TITLE
🐛 [Bug] This Profile causes app crash

### ISSUE THREAD

**Issue by antontranelis** [utopia-os/utopia-ui#50]
Opening that profile makes the app crash:

https://next.docutopia.de/54870c5f-9b37-4bcb-9838-59a76561c4d5

**Comment by ulfgebhardt** [comment]
For me the error occurs here: https://github.com/utopia-os/utopia-map/blob/main/src/api/mapApi.ts#L21

But its my cookies policy preventing the page the page to load - it might be another problem
![image](https://github.com/user-attachments/assets/e40efff3-fb65-4dd5-8a43-7976b85880b0)

![image](https://github.com/user-attachments/assets/0f5ba172-8164-414c-b305-b6480e4405f6)

After accepting cookies I am fine
![image](https://github.com/user-attachments/assets/ee932341-81c9-4700-a96d-e026fc2ffea5)

**Comment by ulfgebhardt** [comment]
For the error you were describing
![image](https://github.com/user-attachments/assets/95297575-aefe-46e9-b149-ad0bbd664cec)

`user_created` is for this case = null
![image](https://github.com/user-attachments/assets/c8cb19a1-06ab-4a44-a115-7437b873e511)
