### ISSUE TITLE
💬 [Question] REOPEN Closed unFINISHED issues now? 

### ISSUE THREAD

**Issue by BobaMende** [utopia-os/utopia-ui#60]
<!-- Question to all from our team:

Three issues closed without comments eventhough the issues are still open. Please do correct the naming 'docutopia" not ...utopiaOS/UI, reopen all issues and my @BobaMende access to (docutopia updates /game at tlgr as well as into all relevant the groups of all of us @antontranelis asap.

**Comment by BobaMende** [comment]
![Screenshot_20241209-134825_Firefox](https://github.com/user-attachments/assets/9058195b-ccc1-4724-9b17-490acd6ae795)

**Comment by antontranelis** [comment]
Thank you for taking the time to create an issue and contribute to this project. While we truly appreciate your engagement, the issues  #6 and #15 lacks clarity and specific requirements, making it difficult for us to address it effectively.

To ensure we can better understand and discuss your concern, could you please open a discussion instead? This will allow us to collaborate and refine your ideas into actionable tasks before creating an issue.

If you're unsure how to clarify your request, you might consider seeking assistance from technically versed individuals who can help you work out the details. This will ensure that your ideas are clear and actionable for us to address.

You can start a discussion [here](https://github.com/orgs/utopia-os/discussions/new?category=ideas)

Thank you for your understanding and support!

**Comment by Pappmann** [comment]
> Vielen Dank, dass Sie sich die Zeit genommen haben, ein Issue zu erstellen und zu diesem Projekt beizutragen. Wir wissen Ihr Engagement sehr zu schätzen, aber den Themen #6 und #15 mangelt es an Klarheit und spezifischen Anforderungen, so dass es für uns schwierig ist, sie effektiv zu bearbeiten.
> 
> Um sicherzustellen, dass wir Ihr Anliegen besser verstehen und besprechen können, könnten Sie stattdessen bitte eine Diskussion eröffnen. Auf diese Weise können wir zusammenarbeiten und Ihre Ideen in umsetzbare Aufgaben umwandeln, bevor wir ein Problem erstellen.
> 
> Wenn Sie unsicher sind, wie Sie Ihr Anliegen formulieren sollen, können Sie sich an technisch versierte einzelne Menschen wenden, die Ihnen bei der Ausarbeitung der Details helfen können. So stellen Sie sicher, dass Ihre Ideen klar sind und wir sie umsetzen können.
> 
> Sie können eine Diskussion [hier](https://github.com/orgs/utopia-os/discussions/new?category=ideas) beginnen.
> 
> Wir danken Ihnen für Ihr Verständnis und Ihre Unterstützung!

@antontranelis Inwieweit bezieht sich deine Antwort auf das Anliegen von @BobaMende ? 

Sie ist sachlich  formuliert und es ist kaum Resonanz zum Anliegen zu erkennen.

Please reopen this issue.
